### ISSUE TITLE
Chrome as Default browser flow

### ISSUE THREAD

**Issue by ricburton** [balance-io/Balance#24]
![image](https://user-images.githubusercontent.com/438160/154984024-38fe4e28-83a6-4de6-873c-9a9f01b61452.jpeg)

Right now if someone has set Chrome to be their default iOS browser the app bounces them out to Chrome instead of Safari.

We need to look into sending users straight into Safari *even if* Chrome is their default.

**Comment by DimitarNestorov** [comment]
Fixed in 8b765c7b496d3f219c938ab9dc7a2631a9cc1b0e
