### ISSUE TITLE
Remove "See All" from Wallets Screen

### ISSUE THREAD

**Issue by ricburton** [balance-io/Balance#28]
This feels unneeded:

<img width="420" alt="CleanShot 2022-02-28 at 09 21 48@2x" src="https://user-images.githubusercontent.com/438160/156029042-764aaec5-cf0d-4551-a167-39fa6f4a4e2e.png">

**Comment by ivanvorobei** [comment]
@ricburton did

**Comment by ricburton** [comment]
Thank you @ivanvorobei!
